# Site settings
title: Monetize
email: jc@bitool.io
description: > # this means to ignore newlines until "baseurl:"
  Stay hungry, stay foolish.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bitool.io" # the base hostname & protocol for your site
twitter_username: a6512c
github_username:  caozhen

timezone: Asia/Shanghai
# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
